### ISSUE TITLE
Plugins have some typos in their options

### ISSUE THREAD

**Issue by NikSneMC** [KaylorBen/nixcord#13]
That option should be named autoDisable
https://github.com/KaylorBen/nixcord/blob/b07dadc8822890dd60b603c2b6451c6f38526e24/plugins.nix#L2550-L2556

That option is named persistState in the plugin settings
https://github.com/KaylorBen/nixcord/blob/b07dadc8822890dd60b603c2b6451c6f38526e24/plugins.nix#L2547-L2549

**Comment by KaylorBen** [comment]
fixed by https://github.com/KaylorBen/nixcord/pull/14 --closed
