### ISSUE TITLE
Question: Is it possible to modify `~/.config/vesktop/state.json` and `~/.config/vesktop/settings.json`?

### ISSUE THREAD

**Issue by purrpurrn** [KaylorBen/nixcord#18]
Is it possible to modify `~/.config/vesktop/state.json` and `~/.config/vesktop/settings.json`?

**Comment by KaylorBen** [comment]
Ye there's no reason this can't be implimented. I'll start working on it for at least Vesktop.
``~/.config/discord/settings.json`` should also be added, but it has some really ugly JSON fields that'll take a bit.

**Comment by KaylorBen** [comment]
Let me know if PR #19 works for you. I haven't gotten a chance to actually test it, but it should work since its pretty simple. Only thing I could imagine is weird interaction with mkVencordCfg messing up the JSON.

**Comment by KaylorBen** [comment]
should be fixed now after merge of PR #19. lmk if you still get the weird default error, but should be fixed

**Comment by joinemm** [comment]
Also, this would fundamentally not work as if `state.json` is read only, vencord crashes.

**Comment by joinemm** [comment]
Judging by the dev's comments it's not likely they will fix it: https://github.com/Vencord/Vesktop/issues/220

But using the patch posted in that thread can be used as a workaround

**Comment by KaylorBen** [comment]
Ye this doesn't look good for this working. I'll leave the options in, but might add warnings to the documentation that this isn't really supported. That or they could be removed entirely. I might also be possible to create a shell script that generates this file outside of the nix store, but idk what that implementation would look like / if its a good idea.
