### ISSUE TITLE
Home Manager unable to rebuild when the vesktop package is enabled. 

### ISSUE THREAD

**Issue by Ysujy** [KaylorBen/nixcord#21]
Firstly, thank you for the awesome project. Have been looking for something like this for a while.

Anyway. I might be misunderstanding the documentation, but using my attached config home manager is unable to rebuild the system. Commenting out the vesktop package fixes the problem. 

```
{ pkgs, config, ... }: 
{
  programs.nixcord = {
    enable = true;  # enable Nixcord. Also installs discord package
    vesktop.enable = true;
    config = {
      frameless = true; # set some Vencord options
      transparent = true;
      plugins = {
        anonymiseFileNames = {
	 enable = true;
	 anonymiseByDefault = true;
	};
	fakeNitro.enable = true;  
	callTimer.enable = true;
	clearURLs.enable = true;
	disableCallIdle.enable = true;
	fixCodeblockGap.enable = true;
	fixYoutubeEmbeds.enable = true;
	gameActivityToggle.enable = true;
	gifPaste.enable = true;
	iLoveSpam.enable = true;
	messageLogger.enable = true;
	moreKaomoji.enable = true;
        noScreensharePreview.enable = true;
        platformIndicators.enable = true;
	previewMessage.enable = true;
	reverseImageSearch.enable = true;
	searchReply.enable = true;
	summaries.enable = true;
	sendTimestamps.enable = true;
	shikiCodeblocks.enable = true;
	showConnections.enable = true;
	showHiddenChannels.enable = true;
	showHiddenThings.enable = true;
        spotifyCrack.enable = true;
	translate.enable = true;
        userVoiceShow.enable = true;
	vcNarrator.enable = true;
	voiceMessages.enable = true;
	youtubeAdblock.enable = true;
      };
    };
    extraConfig = {
    };
  };
}
```

Thank you in advance

**Comment by KaylorBen** [comment]
Can you post the error code you are getting?

It is likely the settings.json file for Vesktop already exists and is causing a collision.

**Comment by Ysujy** [comment]
> It is likely the settings.json file for Vesktop already exists and is causing a collision.
That seems to have done the trick.

I was getting the following error:
```
warning: Git tree '/etc/nixos' is dirty
building the system configuration...
warning: Git tree '/etc/nixos' is dirty
activating the configuration...
setting up /etc...
reloading user units for cary...
restarting sysinit-reactivation.target
restarting the following units: home-manager-cary.service
Failed to restart home-manager-cary.service
the following new units were started: libvirtd.service, run-credentials-systemd\x2dtmpfiles\x2dresetup.service.mount, sysinit-reactivation.target, systemd-tmpfiles-resetup.service
warning: the following units failed: home-manager-cary.service
× home-manager-cary.service - Home Manager environment for cary
     Loaded: loaded (/etc/systemd/system/home-manager-cary.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-09-14 02:21:24 CEST; 272ms ago
   Duration: 32min 29.996s
 Invocation: b2d6375c81a243fcb331d06a087d4047
    Process: 5048 ExecStart=/nix/store/hh1d3nhigpky6d6shbnpxmhv4385fhgs-hm-setup-env /nix/store/gvw9pzvnl8n9f3xvfw6civc79hqnjw79-home-manager-generation (code=exited, status=1/FAILURE)
   Main PID: 5048 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
   Mem peak: 5.7M
        CPU: 118ms

Sep 14 02:21:24 nixos hm-activate-cary[5224]: Please do one of the following:
Sep 14 02:21:24 nixos hm-activate-cary[5224]: - Move or remove the above files and try again.
Sep 14 02:21:24 nixos hm-activate-cary[5224]: - In standalone mode, use 'home-manager switch -b backup' to back up
Sep 14 02:21:24 nixos hm-activate-cary[5224]:   files automatically.
Sep 14 02:21:24 nixos hm-activate-cary[5224]: - When used as a NixOS or nix-darwin module, set
Sep 14 02:21:24 nixos hm-activate-cary[5224]:     'home-manager.backupFileExtension'
Sep 14 02:21:24 nixos hm-activate-cary[5224]:   to, for example, 'backup' and rebuild.
Sep 14 02:21:24 nixos systemd[1]: home-manager-cary.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 02:21:24 nixos systemd[1]: home-manager-cary.service: Failed with result 'exit-code'.
Sep 14 02:21:24 nixos systemd[1]: Failed to start Home Manager environment for cary.
warning: error(s) occurred while switching to the new configuration
```

Thank you for the help!

**Comment by NikSneMC** [comment]
> > It is likely the settings.json file for Vesktop already exists and is causing a collision.
> 
> That seems to have done the trick.
> 
> I was getting the following error:
> 
> ```
> warning: Git tree '/etc/nixos' is dirty
> building the system configuration...
> warning: Git tree '/etc/nixos' is dirty
> activating the configuration...
> setting up /etc...
> reloading user units for cary...
> restarting sysinit-reactivation.target
> restarting the following units: home-manager-cary.service
> Failed to restart home-manager-cary.service
> the following new units were started: libvirtd.service, run-credentials-systemd\x2dtmpfiles\x2dresetup.service.mount, sysinit-reactivation.target, systemd-tmpfiles-resetup.service
> warning: the following units failed: home-manager-cary.service
> × home-manager-cary.service - Home Manager environment for cary
>      Loaded: loaded (/etc/systemd/system/home-manager-cary.service; enabled; preset: enabled)
>      Active: failed (Result: exit-code) since Sat 2024-09-14 02:21:24 CEST; 272ms ago
>    Duration: 32min 29.996s
>  Invocation: b2d6375c81a243fcb331d06a087d4047
>     Process: 5048 ExecStart=/nix/store/hh1d3nhigpky6d6shbnpxmhv4385fhgs-hm-setup-env /nix/store/gvw9pzvnl8n9f3xvfw6civc79hqnjw79-home-manager-generation (code=exited, status=1/FAILURE)
>    Main PID: 5048 (code=exited, status=1/FAILURE)
>          IP: 0B in, 0B out
>    Mem peak: 5.7M
>         CPU: 118ms
> 
> Sep 14 02:21:24 nixos hm-activate-cary[5224]: Please do one of the following:
> Sep 14 02:21:24 nixos hm-activate-cary[5224]: - Move or remove the above files and try again.
> Sep 14 02:21:24 nixos hm-activate-cary[5224]: - In standalone mode, use 'home-manager switch -b backup' to back up
> Sep 14 02:21:24 nixos hm-activate-cary[5224]:   files automatically.
> Sep 14 02:21:24 nixos hm-activate-cary[5224]: - When used as a NixOS or nix-darwin module, set
> Sep 14 02:21:24 nixos hm-activate-cary[5224]:     'home-manager.backupFileExtension'
> Sep 14 02:21:24 nixos hm-activate-cary[5224]:   to, for example, 'backup' and rebuild.
> Sep 14 02:21:24 nixos systemd[1]: home-manager-cary.service: Main process exited, code=exited, status=1/FAILURE
> Sep 14 02:21:24 nixos systemd[1]: home-manager-cary.service: Failed with result 'exit-code'.
> Sep 14 02:21:24 nixos systemd[1]: Failed to start Home Manager environment for cary.
> warning: error(s) occurred while switching to the new configuration
> ```
> 
> Thank you for the help!

Can you send the output of `journalctl -xeu home-manager-cary.service`?
