### ISSUE TITLE
Make it usable with configuration.nix

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [KaylorBen/nixcord#25]
Some people perfer not to use flakes, a way to use this in configuration.nix would be nice.

**Comment by KaylorBen** [comment]
I added a default.nix using flake compat. I have not tested it, and I'm not super familiar how channels work, but lmk if it does, or how it can be fixed.

**Comment by SpiderUnderUrBed** [comment]
I am busy right now but ill test it soon!

**Comment by SpiderUnderUrBed** [comment]
I will re-open this issue after testing.
