### ISSUE TITLE
bug: customIdle breaks Friends & Calls

### ISSUE THREAD

**Issue by KP64** [KaylorBen/nixcord#26]
Hi. Love the project.
I haven't been able to call someone, either privately or through server VCs.
Friends aren't shown either in the Friends Tab.
It only happens in nixcord. Everything works as expected when installing default discord.
I pinpointed the issue to having the customIdle plugin enabled.
[Here](https://github.com/KP64/nixos-config) is my config and [here](https://github.com/KP64/nixos-config/blob/master/programs/gaming/discord.nix) is the nixcord file.

**Comment by KaylorBen** [comment]
This is an issue with an incompatibility between the current version of Discord in nixpkgs and the number release of Vencord currently which doesn't include this patch. I'm updating currently and this should be fixed, and also implementing a lockfile to help prevent this in the future.

**Comment by KaylorBen** [comment]
Seems to be fixed after update, let me know if it works for you and I'll close the issue!

**Comment by KP64** [comment]
It works again. Thank you!
