### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by korbosoft** [KaylorBen/nixcord#42]
Doesn't Vencloud already do this?

**Comment by SystematicError** [comment]
If your goal is to backup just your Vencord settings, Vencoud is probably the easiest solution.

However this project's aims are not necessarily that, instead, aiming to allow a user to configure Discord/Vencord via the Nix language; Nix can also be used to declarative configure the state of your entire system and programs with a central file(s) in a reproducible manner. Using Nix or this project won't make your settings automatically sync across devices.

Additionally, using Vencloud would mean having to comply with Vencord's privacy policy, and the fact that your data is stored on a 3rd party server.

**Comment by DontEatOreo** [comment]
To add to what SystematicError said, using Nixcord upholds the Nix reproducibility promise, as the Vencord cloud solution can have its state modified externally, which will break that promise

**Comment by korbosoft** [comment]
I see!
